version: 3

tasks:
  default:
    desc: Default task, builds and runs the project
    deps:
      - run

  build:
    desc: Builds the project
    cmds:
      - go-bindata -o assets.go assets/
      - go build -o release/odh-data-monitor
  run:
    desc: Runs the project
    deps:
      - build
    cmds:
      - ./release/odh-data-monitor {{.CLI_ARGS}}

  dev:
    desc: Runs the project in dev mode
    deps:
      - build
      - clean
    cmds:
      - ./release/odh-data-monitor {{.CLI_ARGS}}

  clean:
    desc: Cleans the project configs
    cmds:
      - rm -r {{.HOME}}/.config/odh-data-monitor