version: 3

tasks:
  default:
    desc: Default task, installs the binary
    deps:
      - install

  build:
    desc: Builds the project
    cmds:
      - go build

  install:
    desc: Installs the project to $GOPATH
    deps:
      - build
    cmds:
      - go install

  run:
    desc: Runs the project
    deps:
      - build
      - install
    cmds:
      - apisense {{.CLI_ARGS}}

  docker-build:
    desc: Builds a fresh docker image
    cmds:
      - docker build --no-cache -t auribuo/apisense:latest .

  docker:
    desc: Builds a fresh docker image and runs the app in a container
    deps:
      - build
      - docker-build
    cmds:
      - docker run -it --rm -p 23232:23232 -p 8080:8080 --name apisense auribuo/apisense:latest

  clean-all:
    desc: Cleans the project
    deps:
      - clean
      - clean-cfg

  clean:
    desc: Cleans the project
    cmds:
      - go clean -i

  clean-cfg:
    desc: Cleans the project configs
    cmds:
      - rm -r {{.HOME}}/.config/apisense
      - rm -r {{.HOME}}/apisense

  release:
    desc: Builds the release binaries
    cmds:
      - rm -rf release/
      - go build -o release/apisense-v.0.2.0-linux-amd64