# This is the example configuration file for apisense.
# All the values displayed are the default values

### LOGGING CONFIGURATION ###
# log:
  # Set the log level. Valid values are: debug, info, warn, error, fatal
  # level: "info"

  # Set the log file. Leave empty to log to stdout.
  # file: ""

### DAEMON CONFIGURATION ###
# daemon:
  # Set the interval in seconds in which the daemon should run. The format is cron (https://www.wikipedia.org/wiki/Cron)
  # interval: "* * * * *"

  # Sets whether the daemon should run a validation run upon startup
  # run_on_startup: true

  # Definition files that start with this prefix are not included
  # ignore_prefix: "_"

  # Enable or disable rpc. Note that if rpc is disabled some commands will not work.
  # rpc: true 

  # Set the discard times of reports. Reports older than this will be discarded.
  # discard:
    # Enable discarding of reports
    # enabled: true

    # Set the discard interval. Reports older than this will be discarded.
    # max_lifetime: "720h"

  # Configure the notifications from the daemon
  # notification:
    # Set whether the daemon should send notifications.
    # enabled: false

    # Set whether the daemon should send notifications only if the report contains errors.
    # only_on_error: true

    # Set the sender email of the notifications
    # sender: ""

    # Set the email address to send notifications to.
    # receiver: ""

    # Set the SMTP server to use for sending notifications.
    # smtp_server: ""

    # Set the SMTP port to use for sending notifications.
    # smtp_port: 587

### SSH CONFIGURATION ###
# ssh:
  # Set the SSH host. Leave empty to allow any host to connect
  # host: ""

  # Set the SSH port.
  # port: 23232

### TUI CONFIGURATION ###
# tui:
  # Set the refresh rate of the tui
  # refresh: 10

### API CONFIGURATION ###
# api:
  # Set the API host. Leave empty to allow any host to connect
  # host: ""

  # Set the API port.
  # port: 8080

  # The API key to use for authentication.
  # key: "apisense-1324h#3u4b5AS6j7_k!8l9m0"

  # Enable authentication
  # auth: true

  # Enable swagger
  # swagger: true

### EXTERNAL VALIDATORS ###
# validation:
  # Define external validators that can be used in the definitions.
  # external_validators: []
