name = "Bluetooth"
endpoint = 'https://mobility.api.opendatahub.com/v2/flat/BluetoothStation/Bluetooth%20Count%20record/2021-12-31T23:00:00.000Z/2022-12-21T23:00:00.000Z?limit=-1&distinct=true&select=mvalue,mvalidtime,mperiod&where=scode.eq."{{ .Name }}",mperiod.eq.3600,sactive.eq.true'
method = "GET"

[[parameters]]
name = "Name"
[[parameters.values]]
value = "Agip_Einstein"
[[parameters.values]]
value = "Agip_Einstein"
