name = "Bluetooth2"
base-url = 'https://mobility.api.opendatahub.com/v2/flat/BluetoothStation/Bluetooth%20Count%20record/2021-12-31T23:00:00.000Z/2022-12-21T23:00:00.000Z'
excluded-validators = []
format = "json"

[[query]]
name = "limit"
value = "-1"

[[query]]
name = "distinct"
value = "true"

[[query]]
name = "select"
value = "mvalue,mvalidtime,mperiod"

[[query]]
name = "where"
value = 'scode.eq."{{ .Name }}",mperiod.eq.3600,sactive.eq.true'

[[variable]]
name = "Name"
constant = false
values = [
    "Agip_Einstein",
    'Buozzi_Fiera'
]

[[result.entry]]
name = "offset"
type = "integer"
min = "none"
max = "none"
required = true
fields = []

[[result.entry]]
name = "limit"
type = "integer"
min = "none"
max = "none"
required = true
fields = []

[[result.entry]]
name = "data"
type = "array"
min = "none"
max = "none"
required = true

[[result.entry.fields]]
name = "mperiod"
type = "integer"
min = "none"
max = "none"
required = true
fields = []

[[result.entry.fields]]
name = "mvalue"
type = "integer"
min = "none"
max = "none"
required = true
fields = []

[[result.entry.fields]]
name = "mvalidtime"
type = "string"
min = "none"
max = "none"
required = true
fields = []
