# The name of the endpoint (used in the report)
name = "Bluetooth"

# The endpoint to call. Variables can be interpolated with {{ .ParamName }} (Go template syntax)
# There are also two builtin functions: Now and Env
# Now is used with the following syntax: {{ .Now "<format>" }} you can find the format here: https://pkg.go.dev/time#Time.Format
# Env is used with the following syntax: {{ .Env "<env_var_name>" }}
base-url = 'https://mobility.api.opendatahub.com/v{{ .ApiVersion }}/flat/BluetoothStation/Bluetooth%20Count%20record/2021-12-31T23:00:00.000Z/2022-12-21T23:00:00.000Z'

# The query parameters to pass to the endpoint. Variables can be interpolated with {{ .ParamName }} (Go template syntax)
[[query]]
# The name of the query parameter
name = "limit"
# The value of the query parameter
value = "-1"

[[query]]
name = "distinct"
value = "true"

[[query]]
name = "select"
value = "mvalue,mvalidtime,mperiod"

[[query]]
name = "where"
value = 'scode.eq."{{ .Name }}",mperiod.eq.3600,sactive.eq.true'

# The format of the response (json or xml)
format = "json"

# Variable definitions
# For all non constant variables, the number of values must be the same and will be used in order to call the endpoint (subject to change)
[[variable]]
# The name of the parameter
name = "Name"
# Whether the parameter is constant or not
constant = false
# The possible values of the parameter
values = [
    "Agip_Einstein",
    'aaa'
]

[[variable]]
name = "ApiVersion"
constant = true
values = [
    "2"
]

# Schema definition of the result
[[result.entry]]
# The name of the field
name = "offset"
# The type of the field (string, integer, float, boolean, object)
type = "integer"
# The minimum value of the field (only for integer and float) set to none if not applicable
min = "none"
# The maximum value of the field (only for integer and float)
max = "none"
# Whether the field is required or not
required = true
# The children of the field (only for object)
fields = []

[[result.entry]]
name = "limit"
type = "integer"
min = "none"
max = "none"
required = true
fields = []

[[result.entry]]
name = "data"
type = "array"
min = "none"
max = "none"
required = true

[[result.entry.fields]]
name = "mperiod"
type = "integer"
min = "none"
max = "none"
required = true
fields = []

[[result.entry.fields]]
name = "mvalue"
type = "integer"
min = "none"
max = "none"
required = true
fields = []

[[result.entry.fields]]
name = "mvalidtime"
type = "string"
min = "none"
max = "none"
required = true
fields = []
