# This is the example configuration file for the ODH Data Monitor.

### DAEMON CONFIGURATION ###
[daemon]
# Set the interval in seconds in which the daemon should run. The format is cron (https://www.wikipedia.org/wiki/Cron)
interval = "* * * * *"

# Set the definition directory. This is the directory where the api definitions are stored.
definitions-dir = "~/.config/odh-data-monitor/definitions.d"

# Definition files that start with this prefix are not included
ignore-prefix = "_"

# Set the report output directory. This is the directory where the reports are stored.
reports-dir = "~/.config/odh-data-monitor/reports"

[daemon.log]
# Set the log level. Valid values are: debug, info, warn, error, fatal, panic
level = "info"

# Set the log file. Leave empty to log to stdout.
file = ""

# Enable pretty log output. This will colorize the log output and print it in a readable format.
# If set to false, the log output will be in JSON format.
pretty = true

# Set to true to force color logging. Only has an effect if pretty is set to true.
force-color = true

[daemon.notification]
# Set whether the daemon should send notifications.
enabled = false

# Set whether the daemon should send notifications only if the report contains errors.
only-on-error = true

# Set the email address to send notifications to.
email = "me@example.com"

# Set the SMTP server to use for sending notifications.
smtp-server = "smtp.example.com"

# Set the SMTP port to use for sending notifications.
smtp-port = 587

# Set the SMTP username to use for sending notifications.
smtp-username = "example"

# Set the SMTP password to use for sending notifications.
smtp-password = "password"

### SSH CONFIGURATION ###
[ssh]
# Set the SSH host. Leave empty to allow any host to connect
host = ""

# Set the SSH port.
port = 23232

[tui]
# Set the filewatcher sleep time