// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health": {
            "get": {
                "description": "Get the health status of the API",
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "operationId": "health",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/reports": {
            "get": {
                "description": "Connect to this endpoint with the ws:// protocol to instantiate a websocket connection to get updates for new reports",
                "tags": [
                    "reports"
                ],
                "summary": "Open a websocket connection to receive notifications",
                "operationId": "ws",
                "responses": {
                    "101": {
                        "description": "Switching Protocols"
                    }
                }
            }
        },
        "/api/reports/:id": {
            "get": {
                "description": "Gets a single report identified by his id",
                "tags": [
                    "reports"
                ],
                "summary": "Get one report",
                "operationId": "report",
                "parameters": [
                    {
                        "type": "string",
                        "description": "json",
                        "name": "format",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "qNg8rJX",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/validation.Report"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "validation.Report": {
            "type": "object",
            "properties": {
                "endpoints": {
                    "description": "Endpoints is a collection of ValidatedEndpoint holding the validation results",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/validation.ValidatedEndpoint"
                    }
                },
                "id": {
                    "description": "Id is a unique identifier for each report",
                    "type": "string"
                },
                "time": {
                    "description": "Time is the timestamp of the report",
                    "type": "string"
                }
            }
        },
        "validation.TestCaseResult": {
            "type": "object",
            "properties": {
                "url": {
                    "description": "Url is the url of the api call (with query parameters)",
                    "type": "string"
                },
                "validatorResults": {
                    "description": "ValidatorResults is the collection of ValidatorResult that describe the result of each validator",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/validation.ValidatorResult"
                    }
                }
            }
        },
        "validation.ValidatedEndpoint": {
            "type": "object",
            "properties": {
                "endpointName": {
                    "description": "EndpointName is he name of the endpoint",
                    "type": "string"
                },
                "testCaseResults": {
                    "description": "TestCaseResults are the collection of TestCaseResult that describe the result of validating a single api call",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/validation.TestCaseResult"
                    }
                }
            }
        },
        "validation.ValidatorResult": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message is the error message of the validator",
                    "type": "string"
                },
                "name": {
                    "description": "Name is the name of the validator",
                    "type": "string"
                },
                "status": {
                    "description": "Status is the status of the validator (success/fail/skipped)",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
